name: lightningdata
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt